"""
    Local-first media indexing and deduplication CLI.
    Copyright (C) 2026  Dario Palladino

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

Artifact-sidecar generator for knowledge-graph tooling (e.g. Graphify).

Emits one Markdown sidecar per indexed file, containing only the deterministic
inventory facts mediactl actually knows (path, hash, timestamps, MOC membership,
duplicate status). Topics, entities, extracted text, and narrative summaries are
intentionally left for later enrichment by an agentic harness (Claude Code) or a
graph compiler (Graphify) — mediactl has no content-understanding pipeline, and
fabricating those fields would misrepresent processing that hasn't happened.

Create-only by default: once a sidecar exists, later runs never overwrite it,
since an agent may have since enriched it by hand. Pass force=True to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import structlog
import yaml
from sqlmodel import Session, select

from mediactl.db.models import File
from mediactl.moc import _ext_to_type

log = structlog.get_logger()


@dataclass
class SidecarResult:
    total: int = 0
    created: int = 0
    skipped_existing: int = 0


def _sidecar_filename(f: File) -> str:
    """Flat, collision-safe filename derived from the full source path."""
    safe = f.path.strip("/").replace("/", "__")
    return f"{safe}.md"


def _moc_year(f: File) -> str:
    for ts in (f.created_at, f.modified_at):
        if ts:
            return ts[:4]
    return "Unknown"


def _moc_links_for_file(f: File) -> list[str]:
    """Reuse mediactl's own by_type/by_year MOC classification (moc.py) so the
    sidecar always points at MOC files mediactl actually generates.
    """
    return [f"[[{_ext_to_type(f.extension or '')}]]", f"[[{_moc_year(f)}]]"]


def _canonical_path(session: Session, f: File) -> str | None:
    if not f.canonical_file_id:
        return None
    canonical = session.get(File, f.canonical_file_id)
    return canonical.path if canonical else None


def _frontmatter(f: File, title: str, mocs: list[str], canonical_path: str | None) -> dict:
    data: dict = {
        "kg_type": "Artifact",
        "artifact_type": f.extension or "unknown",
        "title": title,
        "source_path": f.path,
    }
    if f.sha256:
        data["source_hash"] = f"sha256:{f.sha256}"
    data["created_at"] = f.created_at or ""
    data["modified_at"] = f.modified_at or ""
    data["indexed_at"] = f.indexed_at
    data["status"] = "inventoried"
    data["needs_enrichment"] = True
    if f.is_duplicate and canonical_path:
        data["duplicate_of"] = canonical_path
    data["mocs"] = mocs
    return data


def _render_sidecar(f: File, mocs: list[str], canonical_path: str | None) -> str:
    title = Path(f.filename).stem
    frontmatter = yaml.safe_dump(
        _frontmatter(f, title, mocs, canonical_path), sort_keys=False, allow_unicode=True
    )

    body_lines = [
        f"# {title}",
        "",
        "## Inventory",
        "",
        f"- Source: `{f.path}`",
        f"- Size: {f.size_bytes or 0} bytes",
        f"- MIME type: {f.mime_type or 'unknown'}",
    ]
    if f.sha256:
        body_lines.append(f"- SHA256: `{f.sha256}`")
    if f.is_duplicate and canonical_path:
        body_lines.append(f"- Duplicate of: `{canonical_path}`")
    body_lines += [
        "",
        "## Enrichment Needed",
        "",
        "This sidecar was auto-generated by `mediactl generate-sidecars` from file "
        "inventory only. Topics, entities, extracted text, and a real summary are "
        "still pending — fill in via Claude Code / Graphify processing, then update "
        "this note's `status` and `needs_enrichment` fields by hand.",
        "",
    ]

    return f"---\n{frontmatter}---\n\n" + "\n".join(body_lines) + "\n"


def generate_sidecars(
    session: Session, output_dir: Path, *, force: bool = False, dry_run: bool = False
) -> SidecarResult:
    """Generate Artifact sidecars for every indexed file.

    Args:
        session: Active DB session.
        output_dir: Directory sidecars are written into (flat).
        force: Overwrite sidecars that already exist. Default skips them, since a
            harness may have enriched them by hand since they were created.
        dry_run: If True, log what would be written but don't write.

    Returns:
        SidecarResult with total/created/skipped_existing counts.
    """
    result = SidecarResult()

    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    files = session.exec(select(File).where(File.scan_status == "indexed")).all()

    for f in files:
        result.total += 1
        sidecar_path = output_dir / _sidecar_filename(f)

        if sidecar_path.exists() and not force:
            result.skipped_existing += 1
            log.debug("sidecars.skip_existing", path=str(sidecar_path))
            continue

        mocs = _moc_links_for_file(f)
        canonical_path = _canonical_path(session, f) if f.is_duplicate else None
        content = _render_sidecar(f, mocs, canonical_path)

        if dry_run:
            log.debug("sidecars.dry_run_write", path=str(sidecar_path))
        else:
            sidecar_path.write_text(content, encoding="utf-8")
        result.created += 1

    log.info(
        "sidecars.complete",
        total=result.total,
        created=result.created,
        skipped=result.skipped_existing,
        dry_run=dry_run,
    )
    return result
